version: "3.2"
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: xxxxxxxx
    ports:
      - "3306:3306"
    volumes:
      - "./data/db/mysql:/var/lib/mysql"

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

networks:
  default:
    external:
      name: backbone
